version: '3.9'

x-kong-config:
  &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kongdb
  KONG_PG_HOST: kong_database_pg
  KONG_PG_USER: kongdbuser
  KONG_PG_PASSWORD: kongpassword

x-service-one-ruby:
  &service-one-ruby
  restart: always
  image: ruby:3.0.4
  working_dir: /app
  volumes:
    - ./service-one-ruby:/app
  command: /bin/bash -c "bundle install && bundle exec rackup --host 0.0.0.0 --port 9292"

services:
  kong_migrations:
    image: kong:3.6.0
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      - kong_database_pg
    environment:
      <<: *kong-env
    restart: on-failure

  kong:
    image: kong:3.6.0
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yaml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
    restart: always
    volumes:
      - ./kong.yaml:/opt/kong/kong.yaml

  kong_database_pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: kongdb
      POSTGRES_USER: kongdbuser
      POSTGRES_PASSWORD: kongpassword
    restart: always

  service_one_ruby_replica01:
    <<: *service-one-ruby

  service_one_ruby_replica02:
    <<: *service-one-ruby
